### ISSUE TITLE
Add support for php 7.1

### ISSUE THREAD

**Issue by sgotre** [sgotre/sphp-osx#13]

**Comment by sgotre** [comment]
@maztch 
thanks for your proposal in https://github.com/sgotre/sphp-osx/pull/9/commits/36b4563aee8e7cdf19c23ec6c7575ff613ef7b19

This did not work for me :( the httpd.conf was not updated correctly. 
What should the httpd.conf look like when using php71?

httpd.conf before:
```
# Brew PHP LoadModule for `sphp` switcher
#LoadModule php5_module /usr/local/lib/libphp5.so
LoadModule php7_module /usr/local/lib/libphp7.so

```



httpd.conf after:
```
# Brew PHP LoadModule for `sphp` switcher
#LoadModule php5_module /usr/local/lib/libphp5.so
#LoadModule php7_module /usr/local/lib/libphp7.so

```

the libphp for 71 was not added... just commented out the other ones. 

thanks for contributing!

**Comment by maztch** [comment]
Yah, sorry, it's because i have not linked modules there (sometimes i need one php version in apache and other in terminal) and merged with my not compatible custom path.

My .htaccess:

# Brew PHP LoadModule
LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so
#LoadModule php7_module /usr/local/opt/php70/libexec/apache2/libphp7.so
#LoadModule php7_module /usr/local/opt/php71/libexec/apache2/libphp7.so

I'll change it to check first if there is a full version (major+minor) and then for a simple major version :) to make it compatible.

**Comment by sgotre** [comment]
I now merged your changes, tested and it worked now. thank you!
